
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: justificador_development

production:
  <<: *default
  host: 10.0.0.13
  database: justificador
  socket: /var/lib/mysql/mysql.sock
#  password: <%= ENV['JUSTIFICADOR_DATABASE_PASSWORD'] %>

production_cimavnetmultix:
  adapter: mysql2
  host: 10.0.0.13
  encoding: utf8
  pool: 5
  username: netmultix
  password: <%= ENV.fetch('PASSWD_NETMULTIX')%>
  socket: /tmp/mysql.sock
  database: cimavnetmultix
